apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bf2fg1fxc-python 
  janus-idp.io/tekton: bf2fg1fxc-python
  backstage.io/kubernetes-id: bf2fg1fxc-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bf2fg1fxc-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml